fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: >
          (?x)^(
              package-lock\.json
          )$
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
        exclude: ^backend/users/tasks\.py$
      - id: detect-private-key
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.15.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.0"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: biome
        name: biome-local
        entry: pnpm exec biome check --write
        language: system
        types: [file]
        files: \.(js|jsx|ts|tsx)$
        exclude: ^frontend/js/api/
        pass_filenames: true
      - id: tsc
        name: tsc-local
        entry: pnpm run tsc
        language: system
        types: [file]
        files: \.(ts|tsx)$
        pass_filenames: false
      - id: missing-migrations
        name: missing-migrations-local
        entry: >
          bash -lc 'if rg -Fq "{{ project_name }}" pyproject.toml; then
          echo "Skipping missing migrations check in template mode";
          exit 0; fi;
          uv run python backend/manage.py makemigrations --check'
        language: system
        # Only run missing migration check if migration-generating files have changed:
        files: (.*/?(settings|migrations|models)/.+|.+models\.py|.+constants\.py|.+choices\.py|.+pyproject\.toml)
        pass_filenames: false
      - id: backend-schema
        name: backend-schema-local
        entry: >
          bash -lc 'if rg -Fq "{{ project_name }}" pyproject.toml; then
          echo "Skipping backend schema generation in template mode";
          exit 0; fi;
          uv run python backend/manage.py export_openapi_schema --api {{project_name}}.api.api --output backend/schema.openapi'
        language: system
        files: ^backend/
        pass_filenames: false
      - id: frontend-api
        name: frontend-api-local
        entry: pnpm run openapi-ts
        language: system
        files: backend/schema\.openapi$
        pass_filenames: false
