// This file is auto-generated by @hey-api/openapi-ts

export const $RestCheckResponseSchema = {
    properties: {
        message: {
            title: 'Message',
            type: 'string'
        }
    },
    required: ['message'],
    title: 'RestCheckResponseSchema',
    type: 'object'
} as const;

export const $UserSchema = {
    properties: {
        id: {
            title: 'Id',
            type: 'integer'
        },
        email: {
            title: 'Email',
            type: 'string'
        },
        is_active: {
            title: 'Is Active',
            type: 'boolean'
        },
        is_staff: {
            title: 'Is Staff',
            type: 'boolean'
        },
        is_superuser: {
            title: 'Is Superuser',
            type: 'boolean'
        },
        created: {
            format: 'date-time',
            title: 'Created',
            type: 'string'
        },
        modified: {
            format: 'date-time',
            title: 'Modified',
            type: 'string'
        },
        last_login: {
            anyOf: [
                {
                    format: 'date-time',
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Login'
        }
    },
    required: ['id', 'email', 'is_active', 'is_staff', 'is_superuser', 'created', 'modified'],
    title: 'UserSchema',
    type: 'object'
} as const;

export const $UsersListSchema = {
    properties: {
        count: {
            title: 'Count',
            type: 'integer'
        },
        next: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next'
        },
        previous: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Previous'
        },
        results: {
            items: {
                '$ref': '#/components/schemas/UserSchema'
            },
            title: 'Results',
            type: 'array'
        }
    },
    required: ['count', 'results'],
    title: 'UsersListSchema',
    type: 'object'
} as const;

export const $UserCreateSchema = {
    properties: {
        email: {
            title: 'Email',
            type: 'string'
        },
        password: {
            title: 'Password',
            type: 'string'
        }
    },
    required: ['email', 'password'],
    title: 'UserCreateSchema',
    type: 'object'
} as const;

export const $UserUpdateSchema = {
    properties: {
        email: {
            title: 'Email',
            type: 'string'
        },
        password: {
            title: 'Password',
            type: 'string'
        }
    },
    required: ['email', 'password'],
    title: 'UserUpdateSchema',
    type: 'object'
} as const;

export const $UserPatchSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    title: 'UserPatchSchema',
    type: 'object'
} as const;