// This file is auto-generated by @hey-api/openapi-ts

export type RestCheckResponseSchema = {
  message: string;
};

export type UserSchema = {
  id: number;
  email: string;
  is_active: boolean;
  is_staff: boolean;
  is_superuser: boolean;
  created: string;
  modified: string;
  last_login?: string | null;
};

export type UsersListSchema = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<UserSchema>;
};

export type UserCreateSchema = {
  email: string;
  password: string;
};

export type UserUpdateSchema = {
  email: string;
  password: string;
};

export type UserPatchSchema = {
  email?: string | null;
  password?: string | null;
};

export type RestRestCheckRetrieveResponse = RestCheckResponseSchema;

export type UsersListResponse = UsersListSchema;

export type UsersCreateData = {
  requestBody: UserCreateSchema;
};

export type UsersCreateResponse = UserSchema;

export type UsersRetrieveData = {
  userId: number;
};

export type UsersRetrieveResponse = UserSchema;

export type UsersUpdateData = {
  requestBody: UserUpdateSchema;
  userId: number;
};

export type UsersUpdateResponse = UserSchema;

export type UsersPartialUpdateData = {
  requestBody: UserPatchSchema;
  userId: number;
};

export type UsersPartialUpdateResponse = UserSchema;

export type UsersDestroyData = {
  userId: number;
};

export type UsersDestroyResponse = void;

export type $OpenApiTs = {
  '/api/rest/rest-check/': {
    get: {
      res: {
        /**
         * OK
         */
        200: RestCheckResponseSchema;
      };
    };
  };
  '/api/users/': {
    get: {
      res: {
        /**
         * OK
         */
        200: UsersListSchema;
      };
    };
    post: {
      req: UsersCreateData;
      res: {
        /**
         * Created
         */
        201: UserSchema;
      };
    };
  };
  '/api/users/{user_id}/': {
    get: {
      req: UsersRetrieveData;
      res: {
        /**
         * OK
         */
        200: UserSchema;
      };
    };
    put: {
      req: UsersUpdateData;
      res: {
        /**
         * OK
         */
        200: UserSchema;
      };
    };
    patch: {
      req: UsersPartialUpdateData;
      res: {
        /**
         * OK
         */
        200: UserSchema;
      };
    };
    delete: {
      req: UsersDestroyData;
      res: {
        /**
         * No Content
         */
        204: void;
      };
    };
  };
};
